AWSTemplateFormatVersion: 2010-09-09
Description: {{cookiecutter.project_name}}
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs12.x
    MemorySize: 128

Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambda.handler
      Description: A sample Lambda function.
      Policies:
        - AWSLambdaBasicExecutionRole
